=== kaismi/snmp-mock-agent/src/test/resources/mos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified"
           elementFormDefault="qualified" targetNamespace="http://www.kaismi.at/mos">
    <xs:element xmlns:mo="http://www.kaismi.at/mos" name="mos" type="mo:mosType"/>
    <xs:complexType name="moType">
        <xs:sequence>
            <xs:element name="oid" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
            <xs:element name="access">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="READ_ONLY"/>
                        <xs:enumeration value="WRITE_ONLY"/>
                        <xs:enumeration value="READ_WRITE"/>
                        <xs:enumeration value="READ_CREATE"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="mosType">
        <xs:sequence>
            <xs:element xmlns:mo="http://www.kaismi.at/mos" type="mo:moType" name="mo" maxOccurs="unbounded"
                        minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== kaismi/snmp-mock-agent/src/test/resources/mosWithShema.xml
<?xml version="1.0" encoding="UTF-8"?>
<mos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.kaismi.at/mos"
     xsi:schemaLocation="http://www.kaismi.at/mos mos.xsd">
    <mo>
        <oid>.1.3.6.1.4.1.29671.1.1.2.1.2.0.81.67.82.76.80.98.54</oid>
        <value>8230_Test01_911345678_WLAN</value>
        <access>READ_ONLY</access>
    </mo>
    <mo>
        <oid>.1.3.6.1.4.1.29671.1.1.2.1.2.0.56.66.111.49.80.99.54</oid>
        <value>LAB-2-KLU - switch</value>
        <access>READ_ONLY</access>
    </mo>
</mos>
